2025-11-01 12:39:37,451 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55961 - "PATCH /order/9 HTTP/1.1" 500
2025-11-01 12:39:37,453 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 387, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 288, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\app\routes\order.py", line 166, in comprehensive_update_order
    result = await session.exec(statement)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlmodel\ext\asyncio\session.py", line 98, in exec
    result = await greenlet_spawn(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlmodel\orm\session.py", line 83, in exec
    results = super().execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1633, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 715, in _compile_w_cache
    compiled_sql = self._compiler(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 1446, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 886, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 932, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 138, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 4781, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\base.py", line 701, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 447, in create_for_statement
    return cls._create_orm_context(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 1215, in _create_orm_context
    opt.process_compile_state(self)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\strategy_options.py", line 915, in process_compile_state
    self._process(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\strategy_options.py", line 1143, in _process
    loader.process_compile_state(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\strategy_options.py", line 1717, in process_compile_state
    keys = self._prepare_for_compile_state(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\strategy_options.py", line 2077, in _prepare_for_compile_state
    self._raise_for_no_match(parent_loader, mapper_entities)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\strategy_options.py", line 1627, in _raise_for_no_match
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapped class Mapper[OrderList(tbl_OrderList)] does not apply to any of the root entities in this query, e.g. Mapper[Order(tbl_Order)]. Please specify the full path from one of the root entities to the target attribute. 
2025-11-01 12:51:00,796 - uvicorn.error - INFO - server:264 - Shutting down
2025-11-01 12:51:00,906 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-11-01 12:51:00,906 - app - INFO - config:33 - Application shutdown.....................................
2025-11-01 12:51:00,907 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-11-01 12:51:00,908 - uvicorn.error - INFO - server:94 - Finished server process [12376]
2025-11-01 12:51:02,145 - app - INFO - config:31 - Application startup......................................
2025-11-01 12:51:02,149 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 12:51:02,190 - uvicorn.error - ERROR - on:134 - Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\_compat.py", line 53, in asyncio_run
    return loop.run_until_complete(main)
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\server.py", line 70, in serve
    with self.capture_signals():
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\server.py", line 331, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 701, in lifespan
    await receive()
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
  File "C:\Users\MS511\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

2025-11-01 12:51:03,394 - app - INFO - config:31 - Application startup......................................
2025-11-01 12:51:03,398 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 12:51:30,181 - app - INFO - config:31 - Application startup......................................
2025-11-01 12:51:30,185 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 12:51:35,764 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:56090 - "PATCH /order/9 HTTP/1.1" 200
2025-11-01 14:35:54,775 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61212 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 14:37:47,092 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64926 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 14:37:48,219 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64931 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:37:48,236 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64933 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 14:37:48,251 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64935 - "GET /order/get-order-by-status-by-patient-id/?patient_id=13&order_status=Created HTTP/1.1" 200
2025-11-01 14:37:57,566 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64939 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:37:57,576 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64941 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 14:37:57,588 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64943 - "GET /order/get-order-by-status-by-patient-id/?patient_id=13&order_status=Created HTTP/1.1" 200
2025-11-01 14:38:00,351 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64945 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:38:00,775 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64947 - "PATCH /order/9 HTTP/1.1" 200
2025-11-01 14:38:00,787 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64949 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 14:38:28,314 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64957 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:38:35,574 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64959 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:38:52,664 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64967 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:39:05,980 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64969 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:39:05,991 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:64971 - "PATCH /patient/None HTTP/1.1" 404
2025-11-01 14:56:45,717 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:65470 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 14:56:50,423 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:65475 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 14:56:50,433 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:65477 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 14:56:50,445 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:65479 - "GET /order/get-order-by-status-by-patient-id/?patient_id=13&order_status=Created HTTP/1.1" 200
2025-11-01 15:13:15,079 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49787 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:13:47,083 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49807 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:13:47,093 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49809 - "GET /patient/7439340671 HTTP/1.1" 404
2025-11-01 15:13:55,197 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49814 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:13:59,583 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49817 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:13,669 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49833 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:17,275 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49835 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:17,284 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49837 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:17,293 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49839 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:48,472 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49848 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:14:51,955 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49850 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:17,951 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49854 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:28,647 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49861 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:30,342 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49863 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:31,279 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49865 - "POST /patient/ HTTP/1.1" 201
2025-11-01 15:15:31,290 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49867 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:15:40,801 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49869 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:40,810 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49871 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:15:44,912 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49874 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:44,921 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49876 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:15:46,855 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49878 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:15:46,864 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49880 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:16:08,269 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49882 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:08,277 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49884 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:08,509 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49886 - "GET /patient/waiting-for-consultation-dates/ HTTP/1.1" 200
2025-11-01 15:16:12,671 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49888 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:12,680 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49890 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:12,905 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49892 - "GET /patient/awaiting-for-consultation-by-date/2025-11-01 HTTP/1.1" 200
2025-11-01 15:16:18,026 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49897 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:18,035 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49899 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:18,304 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49901 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:16:26,522 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49908 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:26,532 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49910 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:26,761 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49912 - "GET /disease/ HTTP/1.1" 200
2025-11-01 15:16:28,743 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49914 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:28,752 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49916 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:29,050 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49918 - "GET /drug/read-drug-by-type/2 HTTP/1.1" 200
2025-11-01 15:16:31,082 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49920 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:31,090 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49922 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:32,261 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49924 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:32,271 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49926 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:33,191 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49928 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:33,200 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49930 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:34,213 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49935 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:34,222 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49937 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:37,024 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49939 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:37,033 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49941 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:38,886 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49943 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:38,896 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49945 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:39,188 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49947 - "GET /user/read-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:39,196 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49949 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:16:39,217 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49951 - "POST /order/ HTTP/1.1" 201
2025-11-01 15:16:39,229 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49953 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:16:53,002 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49955 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:53,011 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49957 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:16:53,021 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49959 - "GET /user/role-by-telegram-id/87384626 HTTP/1.1" 200
2025-11-01 15:17:20,224 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49964 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:17:20,233 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49966 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:17:20,245 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49968 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:17:33,125 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49976 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:17:33,135 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49978 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:17:33,146 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49980 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:17:36,011 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49982 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:17:39,266 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49984 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:17:39,558 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49986 - "PATCH /order/10 HTTP/1.1" 200
2025-11-01 15:17:39,567 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49988 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:17:54,444 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49990 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:18:20,276 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:49994 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:18:25,986 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50000 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:18:52,779 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50003 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:18:52,799 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50005 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:18:52,808 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50007 - "PATCH /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:18:53,017 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50009 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:19:24,016 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50013 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:19:24,026 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50015 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:21:35,808 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50117 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:21:39,549 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50123 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:21:39,557 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50125 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:21:39,570 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50127 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:21:54,528 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50135 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:21:54,538 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50137 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:21:54,546 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50139 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:22:05,767 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50144 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:22:12,895 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50148 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:22:17,606 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50151 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:29:45,043 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50267 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:29:47,869 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50274 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:29:47,878 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50276 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:29:47,891 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50278 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:29:55,888 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50284 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:30:05,509 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50287 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:30:11,856 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50292 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:30:11,865 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50294 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:31:39,573 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50324 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:31:40,904 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50329 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:31:40,913 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50331 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:31:40,926 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50333 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:31:45,035 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50337 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:31:49,763 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50339 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:31:53,740 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50346 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:31:53,751 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50348 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:38:58,695 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50466 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:39:01,333 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50471 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:39:01,342 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50473 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:39:01,355 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50475 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:39:07,177 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50479 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:39:13,769 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50483 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:39:22,417 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50490 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:39:22,427 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50492 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:39:57,136 - uvicorn.error - INFO - server:264 - Shutting down
2025-11-01 15:39:57,243 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-11-01 15:39:57,244 - app - INFO - config:33 - Application shutdown.....................................
2025-11-01 15:39:57,245 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-11-01 15:39:57,246 - uvicorn.error - INFO - server:94 - Finished server process [16312]
2025-11-01 15:44:16,049 - app - INFO - config:31 - Application startup......................................
2025-11-01 15:44:16,053 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 15:44:22,457 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50762 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:46:19,607 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50819 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:46:25,063 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50823 - "POST /payment/ HTTP/1.1" 422
2025-11-01 15:46:37,658 - uvicorn.error - INFO - server:264 - Shutting down
2025-11-01 15:46:37,765 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-11-01 15:46:37,769 - app - INFO - config:33 - Application shutdown.....................................
2025-11-01 15:46:37,771 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-11-01 15:46:37,772 - uvicorn.error - INFO - server:94 - Finished server process [7232]
2025-11-01 15:46:38,933 - app - INFO - config:31 - Application startup......................................
2025-11-01 15:46:38,937 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 15:46:44,075 - app - INFO - config:31 - Application startup......................................
2025-11-01 15:46:44,080 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-11-01 15:46:49,253 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50851 - "POST /payment/ HTTP/1.1" 404
2025-11-01 15:47:05,052 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50866 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:05,069 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50868 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:47:05,093 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50870 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 200
2025-11-01 15:47:09,784 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50878 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:16,475 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50890 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:20,392 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50897 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:20,411 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50899 - "POST /payment/ HTTP/1.1" 500
2025-11-01 15:47:20,413 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'payment_id'), 'msg': 'Field required', 'input': PaymentList(created_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), user_id=None, payment_refer_code='ندارد', payment_value=Decimal('12'), payment_status_explain=None, order_id=10, updated_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), payment_date=datetime.datetime(2025, 11, 1, 15, 47, 20, 403606), payment_path_file='C:\\Users\\MS511\\Desktop\\Customers\\Dr_Fazel\\Project2\\Fazel_Pharma_TelegramBot\\patient_files\\7439340671\\7439340671_20251101_154710_receipt.jpg', payment_status=<PaymentStatusEnum.NOT_SEEN: 'Not Seen'>, payment_list_id=1)}

2025-11-01 15:47:54,581 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50920 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:54,591 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50922 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:47:54,603 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50925 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 500
2025-11-01 15:47:54,605 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 0, 'payment_list', 0, 'payment_id'), 'msg': 'Field required', 'input': PaymentList(created_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), user_id=None, payment_refer_code='ندارد', payment_value=Decimal('12'), payment_status_explain=None, order_id=10, updated_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), payment_date=datetime.datetime(2025, 11, 1, 15, 47, 20, 403606), payment_path_file='C:\\Users\\MS511\\Desktop\\Customers\\Dr_Fazel\\Project2\\Fazel_Pharma_TelegramBot\\patient_files\\7439340671\\7439340671_20251101_154710_receipt.jpg', payment_status=<PaymentStatusEnum.NOT_SEEN: 'Not Seen'>, payment_list_id=1)}

2025-11-01 15:47:57,831 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50928 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:47:57,839 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50930 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:47:57,850 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50932 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 500
2025-11-01 15:47:57,851 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 0, 'payment_list', 0, 'payment_id'), 'msg': 'Field required', 'input': PaymentList(created_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), user_id=None, payment_refer_code='ندارد', payment_value=Decimal('12'), payment_status_explain=None, order_id=10, updated_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), payment_date=datetime.datetime(2025, 11, 1, 15, 47, 20, 403606), payment_path_file='C:\\Users\\MS511\\Desktop\\Customers\\Dr_Fazel\\Project2\\Fazel_Pharma_TelegramBot\\patient_files\\7439340671\\7439340671_20251101_154710_receipt.jpg', payment_status=<PaymentStatusEnum.NOT_SEEN: 'Not Seen'>, payment_list_id=1)}

2025-11-01 15:48:08,615 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50938 - "POST /login/access-token HTTP/1.1" 200
2025-11-01 15:48:15,406 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50945 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:48:15,415 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50947 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:48:15,427 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:50949 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 500
2025-11-01 15:48:15,429 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 0, 'payment_list', 0, 'payment_id'), 'msg': 'Field required', 'input': PaymentList(created_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), user_id=None, payment_refer_code='ندارد', payment_value=Decimal('12'), payment_status_explain=None, order_id=10, updated_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), payment_date=datetime.datetime(2025, 11, 1, 15, 47, 20, 403606), payment_path_file='C:\\Users\\MS511\\Desktop\\Customers\\Dr_Fazel\\Project2\\Fazel_Pharma_TelegramBot\\patient_files\\7439340671\\7439340671_20251101_154710_receipt.jpg', payment_status=<PaymentStatusEnum.NOT_SEEN: 'Not Seen'>, payment_list_id=1)}

2025-11-01 15:49:18,792 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:51016 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 403
2025-11-01 15:49:18,822 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:51016 - "GET /favicon.ico HTTP/1.1" 404
2025-11-01 15:49:29,187 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:51021 - "GET /user/role-by-telegram-id/7439340671 HTTP/1.1" 404
2025-11-01 15:49:29,197 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:51023 - "GET /patient/7439340671 HTTP/1.1" 200
2025-11-01 15:49:29,210 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:51025 - "GET /order/get-order-by-status-by-patient-id/?patient_id=14&order_status=Created HTTP/1.1" 500
2025-11-01 15:49:29,212 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 409, in app
    content = await serialize_response(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 252, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 0, 'payment_list', 0, 'payment_id'), 'msg': 'Field required', 'input': PaymentList(created_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), user_id=None, payment_refer_code='ندارد', payment_value=Decimal('12'), payment_status_explain=None, order_id=10, updated_at=datetime.datetime(2025, 11, 1, 12, 17, 20, 404603), payment_date=datetime.datetime(2025, 11, 1, 15, 47, 20, 403606), payment_path_file='C:\\Users\\MS511\\Desktop\\Customers\\Dr_Fazel\\Project2\\Fazel_Pharma_TelegramBot\\patient_files\\7439340671\\7439340671_20251101_154710_receipt.jpg', payment_status=<PaymentStatusEnum.NOT_SEEN: 'Not Seen'>, payment_list_id=1)}

2025-11-01 16:08:11,581 - uvicorn.error - INFO - server:264 - Shutting down
2025-11-01 16:08:11,691 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-11-01 16:08:11,692 - app - INFO - config:33 - Application shutdown.....................................
2025-11-01 16:08:11,693 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-11-01 16:08:11,694 - uvicorn.error - INFO - server:94 - Finished server process [352]
